theme: minima
title: MySite
author: Alex
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Services
    url: /services/
  - title: Portfolio
    url: /portfolio/
  - title: Contact
    url: /contact/
