remote_theme: pages-themes/minimal@v0.2.0
title: My gorgeous website
author: Alex
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Services
    url: /services/
  - title: Portfolio
    url: /portfolio/
  - title: Contact
    url: /contact/
